# Brew Master AI Configuration
# This file configures the data processing pipeline for both local and production environments

# S3 Configuration
s3_bucket: "brew-master-ai-data"
s3_input_prefix: "audio/input/"
s3_output_prefix: "transcripts/"
s3_processed_prefix: "audio/processed/"

# Whisper Configuration
whisper_model: "base"  # tiny, base, small, medium, large
language: "en"
device: "cpu"  # cpu or cuda

# Processing Configuration
max_workers: 4
timeout_seconds: 300

# Storage Configuration (auto-detected based on environment)
# Local: ./data
# Production: /mnt/data

# Logging Configuration
log_level: "INFO"
log_file: "brew_master.log"

# Model Cache Configuration
cache_models: true
model_cache_dir: "models"  # Relative to data directory 